ad/urls.py
from django.contrib import admin
from django.urls import path, include
import  board.urls as board_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(board_urls, namespace="board"))
]

board/urls.py
from django.urls import path
from . import views


app_name="board"


urlpatterns = [
   path('',views.PageWithModalWindow.as_view(), name="test_modal"), 
   path('genres/', views.ListGenre.as_view(), name="list_genres"), 
   path('genres/<int:user_id>/', views.GetSecondPage.as_view(), name="second_page" ),
   path('calendar/', views.Calendar.as_view(), name="calendar"),
   path('xlsx/', views.MyView.as_view(), name="my_view")
   
]

board/models.py
from django.db import models
from treebeard.al_tree import AL_Node
from mptt.models import MPTTModel, TreeForeignKey



# Create your models here.

class Cat(MPTTModel):
    ''' Модель категория '''


    name=models.CharField(max_length=250)
    # slug=models.SlugField(blank=True, unique=True, db_index=True)
    parent=TreeForeignKey("self", on_delete=models.CASCADE, related_name="children", blank=True, null=True, db_index=True)
    node_order_by = ['name']


    def __str__(self):
        return self.name
    

    class MPTTMeta:
        order_insertion_by = ['name']


class Genre(MPTTModel):
    '''
    Тестовая модель mptt
    '''
    
    
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
    related_name='children')
    
    
    def __str__(self) -> str:
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

board/forms.py
from django import forms
from treebeard.forms import movenodeform_factory






      

board/views.py
from typing import Any
from django.shortcuts import render
from django.views import View
from django.views.generic.base import ContextMixin
from django.views import View
from .models import Genre
from datetime import datetime, date
import calendar
from .utils import EventCalendar
import io
from django.http import HttpResponse
from django.views.generic import View
import xlsxwriter
# Create your views here.

class ListGenre(ContextMixin, View):
    '''
    Тестовое представление Жанры(древовидная структура)
    '''


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context=super().get_context_data(**kwargs)
        list_genres=Genre.objects.all()
        context['genres']=list_genres
        return context
    

    def get(self, req, *args, **kwargs):
        context=self.get_context_data()
        context['url']="board:second_page"
        context['user_id']= 3
        return render(req, 'board/base.html', context)

class GetSecondPage(ContextMixin, View):
    '''
    Тестовое представление Жанры(древовидная структура)
    '''


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context=super().get_context_data(**kwargs)
        list_genres=Genre.objects.all()
        context['genres']=list_genres
        return context
    

    def get(self, req, *args, **kwargs):
        context=self.get_context_data()
        
        return render(req, 'board/second_page.html', context)


class Calendar(ContextMixin, View):
    '''
    Тестовая страница с календарём
    '''
    
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return super().get_context_data(**kwargs)


    def get(self, req, *args, **kwargs):
        context=self.get_context_data()
        datetime_today=datetime.now()
        month= int(req.GET.get('month')) if req.GET.get('month') else datetime_today.month
        year= int(req.GET.get('year'))   if req.GET.get('year') else datetime_today.year
        my_year = int(year)
        my_month = int(month)
        # Calculate values for the calendar controls. 1-indexed (Jan = 1)
        my_previous_year = my_year-1
        my_previous_month = my_month - 1
        if my_previous_month == 0:
            my_previous_year = my_year - 1
            my_previous_month = 12
            my_next_year = my_year
            my_next_month = my_month + 1
        if my_next_month == 13:
            my_next_year = my_year + 1
            my_next_month = 1
        # my_year_after_this = my_year + 1
        # my_year_before_this = my_year - 1
        
        
        calendar=EventCalendar()
        
        cal=calendar.formatmonth(year, month, my_previous_month, my_next_month,  my_previous_year, my_next_year)
        context['calendar']=cal
        


        return render(req, 'board/calendar_page.html', context)
    
class PageWithModalWindow(ContextMixin, View):
    '''
    Тестовая страница с модальным окном
    '''

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return super().get_context_data(**kwargs)
    
    def get(self, req, *args, **kwargs):
        context=self.get_context_data()
        return render(req, 'board/base.html')
    

def get_simple_table_data():
    # Simulate a more complex table read.
    return [['1jksgfdkjfs kjsfkjf gaggafgakjfgkajgfjagag', 2, 3], [4, 5, 6], [7, 8, 9]]


class MyView(View):
    def get(self, request):
        # Create an in-memory output file for the new workbook.
        output = io.BytesIO()

        # Even though the final file will be in memory the module uses temp
        # files during assembly for efficiency. To avoid this on servers that
        # don't allow temp files, for example the Google APP Engine, set the
        # 'in_memory' Workbook() constructor option as shown in the docs.
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet()

        # Get some data to write to the spreadsheet.
        data = get_simple_table_data()

        # Write some test data.
        for row_num, columns in enumerate(data):
            for col_num, cell_data in enumerate(columns):
                worksheet.write(row_num, col_num, cell_data)

        # Close the workbook before sending the data.
        workbook.close()

        # Rewind the buffer.
        output.seek(0)

        # Set up the Http response.
        filename = "django_simple.xlsx"
        response = HttpResponse(
            output,
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        response["Content-Disposition"] = "attachment; filename=%s" % filename

        return response

board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
    Главная страница
    {% endblock title %}</title>
    <script src="{% static 'board/assets/scripts_styles/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'board/assets/scripts_styles/custom.js' %}" defer></script>
    <!-- <link rel="stylesheet" href="{% static 'board/assets/scripts_styles/bootstrap.css' %}"/> -->
    <link rel="stylesheet" href="{% static 'board/assets/scripts_styles/custom.css' %}"/>
</head>
<body>
    <a href="{% url 'board:my_view' %}">Кликни</a>
    {% comment %} {% include 'board/genres.html' %} {% endcomment %}
    {% block content %}
    <h1>Контент главной страницы</h1>
    <div class="div-root">
        <div class="div-in-line div-root__flex-elem">
            <div class="">fdghdfghdfghdfghdfghdfgd fsdfsdfsdfsdfsdfsdf dghdfghdfghdfghdfghdfgd fsdfsdfsdfsdfsdfsdf dghdfghdfghdfghdfghdfgd fsdfsdfsdfsdfsdfsdf  </div>
            <div class="div-in-line__flex-box">
                <div class="div-in-line__flex-elem"></div>
            </div>
        </div>
        <div class="div-in-column div-root__flex-elem">
            <div class="div-in-column__flex-elem"> f</div>
            <div class="div-in-column__flex-elem">
                <div class="div-in-line sss">
                    <div class="this">dd</div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <div class="modal__wrapper  ">
        <div class="modal">
            <div class="modal__header">
                <div class="modal__title">Заголовок модалки</div>
                <div class="modal__close">Зарыть</div>
            </div>
            <div class="modal__content">
                content 
                <span class="open-sub-modal">Открыть подмодалку</span>
            </div>
        </div>
    </div>
    <template id="template-sub-modal">
        <div class="modal__wrapper modal__wrapper_visible sub-modal__wrapper">
            <div class="modal sub-modal">
                <div class="modal__header ">
                    <div class="modal__title">Заголовок под модалки</div>
                    <div class="modal__close ">Зарыть под модалку</div>
                </div>
                <div class="modal__content sub-modal__content">
                    content под модалки
                </div>
            </div>
        </div>
    </template>
</body>
</html>

board/templates/board/calendar_page.html
{% extends "board/base.html" %}
{% load calendar_tag %}
{% block content %}
    <h1>Календарь</h1>
    Текущая дата:{{curent_date}}
    {% autoescape off %}
        {{ calendar }}
        {% comment %} {% show_calendar_of_curent_month curent_date %} {% endcomment %}
    {% endautoescape %}
{% endblock content %}

board/templates/board/genres.html
{% load mptt_tags %}
<ul>
{% recursetree genres %}
    <li>
        {{ node.name }}
        {% if not node.is_leaf_node %}
        <ul class="children">
        {{ children }}
        </ul>
        {% endif %}
    </li>
{%endrecursetree %}
</ul>

board/templates/board/inclusion_calendar.html
<div>
    {{calendar}}
</div>

board/templates/board/second_page.html
{% extends "board/base.html" %}
{% block content %}
    <h1>asdasdasd</h1>
{% endblock content %}